# Generated by Django 3.0.4 on 2020-07-11 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_tyb',
            field=models.CharField(choices=[('part time', 'part time'), ('full time', 'full time')], default='', max_length=15),
            preserve_default=False,
        ),
    ]
