# Generated by Django 3.0.4 on 2020-07-11 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_auto_20200711_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='exprince',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='job',
            name='puplish_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.IntegerField(default=0),
        ),
    ]
