# Generated by Django 3.0.4 on 2020-07-11 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_auto_20200711_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='exprince',
            field=models.IntegerField(default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.IntegerField(default=5, max_length=99999),
        ),
    ]
