# Generated by Django 3.0.4 on 2020-07-11 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_auto_20200711_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='exprince',
            field=models.IntegerField(default=1, max_length=2),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.IntegerField(default=5, max_length=5),
        ),
    ]
