# Generated by Django 3.0.4 on 2020-07-12 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_auto_20200712_0151'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='imege',
            field=models.ImageField(default='', upload_to='jobs/'),
            preserve_default=False,
        ),
    ]
