# Generated by Django 3.0.4 on 2020-07-12 06:30

from django.db import migrations, models
import job.models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_job_imege'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='imege',
            field=models.ImageField(upload_to=job.models.uplod_imege),
        ),
    ]
