# Generated by Django 3.0.4 on 2020-07-14 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0016_auto_20200714_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplly_job',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='aplly_job', to='job.job'),
            preserve_default=False,
        ),
    ]
