# Generated by Django 3.0.4 on 2020-07-14 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0017_aplly_job_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplly_job',
            name='create_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
