# Generated by Django 3.0.8 on 2020-07-20 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0019_job_owner_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='owner_name',
            new_name='owner',
        ),
    ]
